"""Client-code generation for D365 custom services and OData entities.

TemplateCodegen — deterministic, offline. Produces a complete runnable
                  Python client (auth + call + error handling) from entity
                  metadata. This is the guaranteed path.
GroqCodegen     — when GROQ_API_KEY is set, llama-3.3-70b refines the same
                  template output against the user's natural-language ask
                  (custom payloads, retry policies, framework variants).
"""
import json

import httpx

from app.d365.edmx import EntityDoc

_CLIENT_TEMPLATE = '''"""Generated by D365 ATLAS — client for {title}."""
import os

import httpx

TENANT_ID = os.environ["D365_TENANT_ID"]
CLIENT_ID = os.environ["D365_CLIENT_ID"]
CLIENT_SECRET = os.environ["D365_CLIENT_SECRET"]
BASE_URL = os.environ["D365_BASE_URL"].rstrip("/")


def get_token() -> str:
    resp = httpx.post(
        f"https://login.microsoftonline.com/{{TENANT_ID}}/oauth2/v2.0/token",
        data={{
            "grant_type": "client_credentials",
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "scope": f"{{BASE_URL}}/.default",
        }},
        timeout=30,
    )
    body = resp.json()
    if "access_token" not in body:
        raise RuntimeError(f"Auth failed: {{body.get('error_description', resp.text)[:200]}}")
    return body["access_token"]


def {func_name}({func_args}) -> dict:
    """{docstring}"""
    token = get_token()
    resp = httpx.{http_method}(
        f"{{BASE_URL}}{path}",
        {body_arg}
        headers={{"Authorization": f"Bearer {{token}}", "Content-Type": "application/json"}},
        timeout=60,
    )
    if resp.status_code == 401:
        raise RuntimeError("Authentication failed — check app registration is a D365 user")
    if resp.status_code == 429:
        raise RuntimeError(f"Throttled — retry after {{resp.headers.get('Retry-After')}}s")
    resp.raise_for_status()
    return resp.json()


if __name__ == "__main__":
    print({example_call})
'''


class TemplateCodegen:
    def generate_service_client(
        self, group: str, service: str, operation: str, sample_payload: dict | None = None
    ) -> str:
        payload = sample_payload or {"_request": {}}
        return _CLIENT_TEMPLATE.format(
            title=f"{group}/{service}/{operation}",
            func_name=operation[0].lower() + operation[1:],
            func_args="payload: dict",
            docstring=f"POST /api/services/{group}/{service}/{operation}",
            http_method="post",
            path=f"/api/services/{group}/{service}/{operation}",
            body_arg="json=payload,",
            example_call=f"{operation[0].lower() + operation[1:]}({json.dumps(payload)})",
        )

    def generate_entity_client(self, doc: EntityDoc) -> str:
        entity_set = doc.entity_set or doc.name
        return _CLIENT_TEMPLATE.format(
            title=f"OData entity {doc.name}",
            func_name=f"query_{doc.name.lower()}",
            func_args='odata_filter: str = "", top: int = 10',
            docstring=(
                f"GET /data/{entity_set} — keys: {', '.join(doc.keys) or 'n/a'}. "
                f"Fields: {', '.join(f['name'] for f in doc.fields[:8])}"
            ),
            http_method="get",
            path=f"/data/{entity_set}?$top={{top}}&$filter={{odata_filter}}",
            body_arg="",
            example_call=f'query_{doc.name.lower()}(top=3)',
        )


class GroqCodegen:
    """LLM-refined generation. Grounds the model with the template output so
    it edits working code instead of hallucinating endpoints."""

    def __init__(self, api_key: str, model: str = "llama-3.3-70b-versatile"):
        self._api_key = api_key
        self._model = model
        self._template = TemplateCodegen()

    async def refine(self, base_code: str, instruction: str) -> str:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={"Authorization": f"Bearer {self._api_key}"},
                json={
                    "model": self._model,
                    "temperature": 0,
                    "messages": [
                        {
                            "role": "system",
                            "content": (
                                "You edit working D365 F&O client code. Keep the auth flow "
                                "and error handling intact. Return only the complete Python "
                                "file, no markdown fences."
                            ),
                        },
                        {
                            "role": "user",
                            "content": f"Instruction: {instruction}\n\nCode:\n{base_code}",
                        },
                    ],
                },
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]
