"""OpenAPI 3.0 spec generation from parsed X++ services — the Swagger that
D365 F&O custom services never had.
"""
from app.d365.xpp import DataContract, ServiceClass, xpp_type_to_schema


def build_openapi(
    service_group: str,
    services: list[ServiceClass],
    contracts: list[DataContract],
    base_url: str = "https://{environment}.axcloud.dynamics.com",
) -> dict:
    contract_names = {c.name for c in contracts}

    schemas = {
        c.name: {
            "type": "object",
            "properties": {
                m.name: xpp_type_to_schema(m.xpp_type, contract_names) for m in c.members
            },
        }
        for c in contracts
    }

    paths = {}
    for svc in services:
        for op in svc.operations:
            request_props = {
                p.name: xpp_type_to_schema(p.xpp_type, contract_names)
                for p in op.parameters
            }
            paths[f"/api/services/{service_group}/{svc.name}/{op.name}"] = {
                "post": {
                    "operationId": f"{svc.name}_{op.name}",
                    "tags": [svc.name],
                    "summary": f"{op.name} — returns {op.return_type}",
                    "security": [{"aadToken": []}],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {"type": "object", "properties": request_props}
                            }
                        },
                    },
                    "responses": {
                        "200": {
                            "description": "Success",
                            "content": {
                                "application/json": {
                                    "schema": xpp_type_to_schema(
                                        op.return_type, contract_names
                                    )
                                }
                            },
                        },
                        "401": {"description": "Authentication failed"},
                        "429": {"description": "Throttled (see Retry-After header)"},
                    },
                }
            }

    return {
        "openapi": "3.0.3",
        "info": {
            "title": f"D365 F&O — {service_group}",
            "version": "1.0.0",
            "description": "Generated by D365 ATLAS from X++ source.",
        },
        "servers": [{"url": base_url}],
        "components": {
            "securitySchemes": {
                "aadToken": {
                    "type": "http",
                    "scheme": "bearer",
                    "description": "AAD v2.0 client-credentials token",
                }
            },
            "schemas": schemas,
        },
        "paths": paths,
    }
