"""Postman collection v2.1 generation from parsed X++ services.

Mirrors the proven pattern: a 'Get Token' request whose test script stores
{{access_token}} as a collection variable, collection-level bearer auth,
secrets referenced from an environment (never stored in the collection).
"""
import json

from app.d365.xpp import ContractMember, DataContract, ServiceClass

_GET_TOKEN_TEST_SCRIPT = [
    "const j = pm.response.json();",
    "if (j && j.access_token) {",
    "  pm.collectionVariables.set('access_token', j.access_token);",
    "  pm.test('Token acquired', function () { pm.expect(j.access_token).to.be.a('string'); });",
    "} else {",
    "  const err = (j && (j.error_description || j.error)) || JSON.stringify(j);",
    "  pm.test('Token acquired', function () { pm.expect.fail(err); });",
    "}",
]


def _sample_value(member: ContractMember, contracts_by_name: dict[str, DataContract]) -> object:
    t = member.xpp_type.lower()
    if member.xpp_type in contracts_by_name:
        return {
            m.name: _sample_value(m, contracts_by_name)
            for m in contracts_by_name[member.xpp_type].members
        }
    if t in ("int", "int64"):
        return 0
    if t == "real":
        return 0.0
    if t == "boolean":
        return False
    return ""


def build_postman_collection(
    service_group: str,
    services: list[ServiceClass],
    contracts: list[DataContract],
) -> dict:
    contracts_by_name = {c.name: c for c in contracts}

    items = [
        {
            "name": "Get Token",
            "event": [
                {
                    "listen": "test",
                    "script": {"type": "text/javascript", "exec": _GET_TOKEN_TEST_SCRIPT},
                }
            ],
            "request": {
                "auth": {"type": "noauth"},
                "method": "POST",
                "header": [],
                "body": {
                    "mode": "urlencoded",
                    "urlencoded": [
                        {"key": "grant_type", "value": "client_credentials"},
                        {"key": "client_id", "value": "{{clientId}}"},
                        {"key": "client_secret", "value": "{{clientSecret}}"},
                        {"key": "scope", "value": "{{baseUrl}}/.default"},
                    ],
                },
                "url": {
                    "raw": "https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token",
                    "protocol": "https",
                    "host": ["login", "microsoftonline", "com"],
                    "path": ["{{tenantId}}", "oauth2", "v2.0", "token"],
                },
                "description": "AAD client-credentials grant. Set tenantId/clientId/"
                "clientSecret in a Postman environment (secret type).",
            },
            "response": [],
        }
    ]

    for svc in services:
        for op in svc.operations:
            sample_body = {
                p.name: _sample_value(p, contracts_by_name) for p in op.parameters
            }
            path_parts = ["api", "services", service_group, svc.name, op.name]
            items.append(
                {
                    "name": f"{svc.name}.{op.name}",
                    "request": {
                        "method": "POST",
                        "header": [{"key": "Content-Type", "value": "application/json"}],
                        "body": {
                            "mode": "raw",
                            "raw": json.dumps(sample_body, indent=2),
                            "options": {"raw": {"language": "json"}},
                        },
                        "url": {
                            "raw": "{{baseUrl}}/" + "/".join(path_parts),
                            "host": ["{{baseUrl}}"],
                            "path": path_parts,
                        },
                        "description": f"Returns {op.return_type}. Inherits bearer "
                        "{{access_token}} from collection auth. Run Get Token first.",
                    },
                    "response": [],
                }
            )

    return {
        "info": {
            "name": f"D365 ATLAS — {service_group}",
            "description": f"Generated by D365 ATLAS from X++ source. "
            f"{sum(len(s.operations) for s in services)} operation(s) across "
            f"{len(services)} service(s).",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{access_token}}", "type": "string"}],
        },
        "variable": [
            {"key": "baseUrl", "value": "", "description": "D365 F&O AOS base URL"},
            {"key": "tenantId", "value": "", "description": "Set in environment"},
            {"key": "clientId", "value": "", "description": "Set in environment"},
            {"key": "clientSecret", "value": "", "description": "Set in environment (secret)"},
            {"key": "access_token", "value": "", "description": "Populated by Get Token"},
        ],
        "item": items,
    }
